# Generated by Django 5.1.2 on 2024-10-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_events_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_date',
            field=models.DateField(),
        ),
    ]
