# Generated by Django 5.1.2 on 2024-10-24 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rsvp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsvp',
            old_name='rsvp',
            new_name='rsvp_status',
        ),
    ]
