# Generated by Django 5.1.2 on 2024-10-26 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_userprofile_user_role'),
        ('events', '0005_rename_rsvp_rsvp_rsvp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.events'),
        ),
        migrations.AlterUniqueTogether(
            name='rsvp',
            unique_together={('event', 'user')},
        ),
    ]
