# Generated by Django 5.1.2 on 2024-10-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_rsvp_event_alter_rsvp_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
