# Generated by Django 5.1.2 on 2024-10-24 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_alter_products_price'),
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='skincare_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.products'),
        ),
        migrations.DeleteModel(
            name='SkincareProduct',
        ),
    ]
