# Generated by Django 5.1.2 on 2024-10-23 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='brand',
            new_name='product_brand',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='description',
            new_name='product_description',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='id',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='product_name',
        ),
    ]
