# Generated by Django 5.1.2 on 2024-10-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.URLField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
