# Generated by Django 5.1.2 on 2024-10-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_alter_products_image'),
        ('catalogue', '0005_alter_products_price'),
    ]

    operations = [
    ]
