# Generated by Django 5.1.2 on 2024-10-25 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_review'),
        ('catalogue', '0007_remove_products_product_image_alter_products_price'),
    ]

    operations = [
    ]
