# Generated by Django 5.1.2 on 2024-10-25 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_merge_20241025_2146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
