# Generated by Django 5.1.2 on 2024-10-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_alter_review_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
