# Generated by Django 5.1.2 on 2024-12-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_adentry_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adentry',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
