# Generated by Django 5.1.2 on 2024-12-02 03:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_adentry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adentry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
