# Generated by Django 5.1.2 on 2024-10-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_role',
            field=models.CharField(default='customer', max_length=50),
            preserve_default=False,
        ),
    ]
