# Generated by Django 5.1.2 on 2024-12-02 04:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=100)),
                ('street_name', models.CharField(max_length=300)),
                ('district', models.CharField(max_length=100)),
                ('gmaps_link', models.URLField(blank=True, max_length=500, null=True)),
                ('store_image', models.URLField(max_length=300)),
            ],
        ),
    ]
