# Generated by Django 5.1 on 2024-10-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locator", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="locations",
            old_name="store_address",
            new_name="street_name",
        ),
        migrations.RemoveField(
            model_name="locations",
            name="website",
        ),
        migrations.AddField(
            model_name="locations",
            name="district",
            field=models.CharField(default="-", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="locations",
            name="gmaps_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
